version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ../db-dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mkt_connect_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
  web:
    tty: true
    stdin_open: true
    build: ./
    container_name: web_application
    privileged: true
    volumes:
      - ./projects:/var/www/html/
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - db
      - redis
